Update dotnet_tests.yaml with resharper

diff --git a/.github/workflows/dotnet_tests.yaml b/.github/workflows/dotnet_tests.yaml
--- a/.github/workflows/dotnet_tests.yaml
+++ b/.github/workflows/dotnet_tests.yaml
@@ -23,3 +23,17 @@ jobs:
       run: dotnet build --no-restore
     - name: Test
       run: dotnet test --no-build --verbosity normal
+
+    - name: Install ReSharper CLT
+      run: |
+        wget -O inspectcode.zip https://download.jetbrains.com/resharper/ReSharper.CommandLineTools.zip
+        unzip inspectcode.zip -d inspectcode
+    - name: Run ReSharper Analysis
+      run: ./inspectcode/inspectcode.sh MyProClip.sln --output=resharper_analysis_results.xml
+
+    - name: Process Analysis Results
+      run: |
+        if grep -q '<Issue Severity="ERROR"' resharper_analysis_results.xml; then
+          echo "Critical issues found. Failing build."
+          exit 1
+        fi
